default[:wildfly][:bucket_region] = 'sa-east-1'
default[:wildfly][:package_object] = 'http://download.jboss.org/wildfly/8.2.0.Final/wildfly-8.2.0.Final.zip'
default[:wildfly][:package_tmp] = '/tmp/wildfly-8.1.0.Final.tar.gz'
default[:wildfly][:extract_dir] = '/opt'
default[:wildfly][:extract_name] = 'wildfly-8.1.0.Final'
default[:wildfly][:home] = '/opt/wildfly'
